name: "KubeLinter scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze Kubernetes Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Perform KubeLinter scan
        uses: stackrox/kube-linter-action@v1.0.6
        with:
          directory: ./demo/helm-charts/templates/
