name: Check Kubernetes YAMLs with kube-linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create scan directory
        shell: bash
        run: mkdir -p yamls
      - name: Generate templated YAML files from Helm chart
        shell: bash
        run: |
          helm template demo/helm-charts --output-dir yamls --name-template test --values demo/helm-charts/values.yaml
      - name: Create ../results directory for SARIF report files
        shell: bash
        run: mkdir -p ../results
      - name: Scan yaml files with kube-linter
        uses: stackrox/kube-linter-action@v1.0.6
        id: kube-linter-action-scan
        with:
          directory: yamls
          format: sarif
          output-file: ../results/kube-linter.sarif
        continue-on-error: true
      - name: Upload SARIF report files to GitHub
        uses: github/codeql-action/upload-sarif@v3
      - name: Verify kube-linter-action succeeded
        shell: bash
        run: |
          echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
          [[ "${{ steps.kube-linter-action-scan.outcome }}" == "success" ]]
